/** Recommended consumer email providers (same set as uniqbd.com admin import). */
export const RECOMMENDED_REGISTRATION_EMAIL_DOMAINS: readonly string[] = [
  'gmail.com',
  'yahoo.com',
  'yahoo.co.uk',
  'yahoo.co.in',
  'outlook.com',
  'hotmail.com',
  'live.com',
  'msn.com',
  'icloud.com',
  'me.com',
  'mac.com',
  'proton.me',
  'protonmail.com',
  'gmx.com',
  'gmx.de',
  'gmx.net',
  'mail.com',
  'zoho.com',
  'yandex.com',
  'yandex.ru',
  'aol.com',
  'tuta.com',
  'tutanota.com',
  'mailfence.com',
  'fastmail.com',
  'mail.ru',
  'inbox.ru',
  'list.ru',
  'rambler.ru',
  'inbox.lv',
  'web.de',
  'freenet.de',
  'posteo.de',
  'runbox.com',
] as const;
