export const ErrorCode = {
  ValidationFailed: 'VALIDATION_FAILED',
  Unauthorized: 'UNAUTHORIZED',
  Forbidden: 'FORBIDDEN',
  NotFound: 'NOT_FOUND',
  Conflict: 'CONFLICT',
  TooManyRequests: 'TOO_MANY_REQUESTS',
  AccountLocked: 'ACCOUNT_LOCKED',
  EmailNotVerified: 'EMAIL_NOT_VERIFIED',
  InvalidCredentials: 'INVALID_CREDENTIALS',
  InvalidToken: 'INVALID_TOKEN',
  TokenExpired: 'TOKEN_EXPIRED',
  SessionRevoked: 'SESSION_REVOKED',
  InactiveAccount: 'INACTIVE_ACCOUNT',
  ProfilePinRequired: 'PROFILE_PIN_REQUIRED',
  ProfilePinInvalid: 'PROFILE_PIN_INVALID',
  ProfileLocked: 'PROFILE_LOCKED',
  ProfileLimitReached: 'PROFILE_LIMIT_REACHED',
  SubscriptionRequired: 'SUBSCRIPTION_REQUIRED',
  SubscriptionInactive: 'SUBSCRIPTION_INACTIVE',
  PlanNotFound: 'PLAN_NOT_FOUND',
  QualityNotAllowed: 'QUALITY_NOT_ALLOWED',
  FeatureNotAllowed: 'FEATURE_NOT_ALLOWED',
  StreamLimitReached: 'STREAM_LIMIT_REACHED',
  DeviceLimitReached: 'DEVICE_LIMIT_REACHED',
  InvalidPlanChange: 'INVALID_PLAN_CHANGE',
  PaymentRequired: 'PAYMENT_REQUIRED',
  PaymentFailed: 'PAYMENT_FAILED',
  PaymentNotFound: 'PAYMENT_NOT_FOUND',
  DuplicatePayment: 'DUPLICATE_PAYMENT',
  WebhookInvalid: 'WEBHOOK_INVALID',
  InvoiceNotFound: 'INVOICE_NOT_FOUND',
  RefundNotAllowed: 'REFUND_NOT_ALLOWED',
  ProviderUnavailable: 'PROVIDER_UNAVAILABLE',
  MovieNotFound: 'MOVIE_NOT_FOUND',
  MovieUnpublished: 'MOVIE_UNPUBLISHED',
  SeriesNotFound: 'SERIES_NOT_FOUND',
  SeasonNotFound: 'SEASON_NOT_FOUND',
  EpisodeNotFound: 'EPISODE_NOT_FOUND',
  MediaNotFound: 'MEDIA_NOT_FOUND',
  LibraryNotFound: 'LIBRARY_NOT_FOUND',
  InvalidLibraryPath: 'INVALID_LIBRARY_PATH',
  ScanInProgress: 'SCAN_IN_PROGRESS',
  ScanNotFound: 'SCAN_NOT_FOUND',
  StorageNotImplemented: 'STORAGE_NOT_IMPLEMENTED',
  SmbConnectionFailed: 'SMB_CONNECTION_FAILED',
  SmbNotFound: 'SMB_NOT_FOUND',
  LicenseRequired: 'LICENSE_REQUIRED',
  LicenseInvalid: 'LICENSE_INVALID',
  LicenseExpired: 'LICENSE_EXPIRED',
  LicenseTrialExpired: 'LICENSE_TRIAL_EXPIRED',
  PlaybackSessionExpired: 'PLAYBACK_SESSION_EXPIRED',
  PlaybackUnavailable: 'PLAYBACK_UNAVAILABLE',
  TrackNotFound: 'TRACK_NOT_FOUND',
  AudioUnavailable: 'AUDIO_UNAVAILABLE',
  SubtitleUnavailable: 'SUBTITLE_UNAVAILABLE',
  Internal: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export type ApiErrorBody = {
  statusCode: number;
  error: ErrorCode;
  message: string;
  details?: unknown;
};
